download_service: hack around Time error
Since updating Rails (and all gems), there is some weirdness with
feeding the macos timestamps (which come from an rss feed) into
ActiveRecord's find_by. I get errors like this:

  ArgumentError: wrong number of arguments (given 1, expected 0)
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/quoting.rb:123:in `quoted_date'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/quoting.rb:245:in `_type_cast'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/sqlite3/quoting.rb:96:in `_type_cast'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/quoting.rb:43:in `type_cast'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/quoting.rb:205:in `block in type_casted_binds'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/quoting.rb:203:in `map'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/quoting.rb:203:in `type_casted_binds'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/sqlite3/database_statements.rb:44:in `exec_query'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:536:in `select_prepared'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:67:in `select_all'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/query_cache.rb:103:in `select_all'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/querying.rb:47:in `find_by_sql'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/statement_cache.rb:150:in `execute'
  .../gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/core.rb:359:in `find_by'
  .../app/services/download_service.rb:122:in `find_or_create_download'
  .../app/services/download_service.rb:66:in `block in download_mac_versions'
  .../app/services/download_service.rb:52:in `each'
  .../app/services/download_service.rb:52:in `download_mac_versions'
  .../lib/tasks/downloads.rake:15:in `block in <top (required)>'

Curiously this doesn't happen with the Windows ones. I confirmed that
date.class here is indeed "Time", but it does stringify different than
the Windows case. Round-tripping it through Time.parse() seems to make
the problem go away. I'm sure there's a more elegant solution, but let's
go with this for now.