resources/guis.yml: separate CommandGit's entry from others
The commit 1e77013 (Adding CommandGit entry to the end of the guis.yml,
2022-08-03) added CommandGit's entry at an incorrect level of
indentation, causing the resources/guis.yml file to be unreadable:

    $ git cat-file -p HEAD:resources/guis.yml | yq .
    Error: bad file '-': yaml: line 390: did not find expected key

Fix this error by re-indenting the new entry properly.

Signed-off-by: Taylor Blau <me@ttaylorr.com>